name: Deploy Go App to EBS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o application main.go

      - name: Package for deployment
        run: zip -r deployment.zip application Procfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload package to S3
        run: |
          aws s3 cp deployment.zip s3://${{ secrets.EBS_S3_BUCKET }}/deployment-${GITHUB_SHA}.zip

      - name: Create new application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EBS_APP_NAME }}" \
            --version-label "build-${GITHUB_SHA}" \
            --source-bundle S3Bucket="${{ secrets.EBS_S3_BUCKET }}",S3Key="deployment-${GITHUB_SHA}.zip"

      - name: Update environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EBS_ENV_NAME }}" \
            --version-label "build-${GITHUB_SHA}"
